[package]
name = "nacos-rust-example"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
nacos-sdk = {version = "0.5", features = ["default"]}
tokio = { version = "1.48.0", features = ["full"] }
